//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal_worker
    {
        public int id { get; set; }
        public int idAnimal { get; set; }
        public int idWorker { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
