//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Animal()
        {
            this.Animal_card = new HashSet<Animal_card>();
            this.Animal_worker = new HashSet<Animal_worker>();
            this.Possible_offspring = new HashSet<Possible_offspring>();
            this.Possible_offspring1 = new HashSet<Possible_offspring>();
        }
    
        public int id { get; set; }
        public int idKind { get; set; }
        public int idCell { get; set; }
        public int idClimatZone { get; set; }
        public string NameOfTheAnimal { get; set; }
        public string nickname { get; set; }
        public string gender { get; set; }
        public System.DateTime dateOfBrith { get; set; }
        public int age { get; set; }
        public int numberOfOffspring { get; set; }
        public string image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal_card> Animal_card { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal_worker> Animal_worker { get; set; }
        public virtual Cell Cell { get; set; }
        public virtual Climate_zone Climate_zone { get; set; }
        public virtual Kind Kind { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Possible_offspring> Possible_offspring { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Possible_offspring> Possible_offspring1 { get; set; }
    }
}
