//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal_card
    {
        public int id { get; set; }
        public Nullable<int> idAnimal { get; set; }
        public string height { get; set; }
        public string weight { get; set; }
        public string disease { get; set; }
        public string vaccinations { get; set; }
    
        public virtual Animal Animal { get; set; }
    }
}
