//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class diet
    {
        public int id { get; set; }
        public int idKind { get; set; }
        public int idFeed { get; set; }
    
        public virtual Feed Feed { get; set; }
        public virtual Kind Kind { get; set; }
    }
}
