//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazprom.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Worker()
        {
            this.Animal_worker = new HashSet<Animal_worker>();
        }
    
        public int id { get; set; }
        public int idPost { get; set; }
        public string fullName { get; set; }
        public System.DateTime dateOfEmployment { get; set; }
        public string gender { get; set; }
        public System.DateTime dateOfBrith { get; set; }
        public double pay { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Animal_worker> Animal_worker { get; set; }
        public virtual Post Post { get; set; }
    }
}
